spring:
  #profiles: 
  #  active: "test"
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

app:
  cors:
    allowed-origin: http://localhost:5173
  jwt:
    secret: ${JWT_SECRET:staticfallbacksecretkeyfordevelopment256bit}
    expiration: 86400000 # 24 hours
  testdata:
    seed: 22
  weights:
    soft-features: 0.8

recommendation:
  mf:
    latent-factors: 50
    learning-rate: 0.015
    regularization: 0.02
    epochs: 100
    beta: 0.4
  hybrid:
    cf: 0.8
    steepness: 0.4
    inflection-point: 10