spring:
  #profiles: 
  #  active: "test"
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

app:
  cors:
    allowed-origin: http://localhost:5173
  jwt:
    secret: ${JWT_SECRET:staticfallbacksecretkeyfordevelopment256bit}
    expiration: 86400000 # 24 hours
  testdata:
    seed: 0 # 0 for random seeding

recommendation:
  weights:
    roast-level: 1.5
    sca-score: 1.1
    altitude: 0.6
    acidity: 1.4
    body: 1.1
    aftertaste: 1.1
    sweetness: 1.1
    bitterness: 1.0
    single-origin: 1.5
    fruity: 1.5
    floral: 1.5
    nutty-cocoa: 1.5
    sweet: 1.5
    spices: 1.5
    vegetal: 1.5
    sour: 1.5
    processing: 1.0
    origins: 0.5
  mf:
    latent-factors: 50
    learning-rate: 0.015
    regularization: 0.02
    epochs: 100
    beta: 0.4
  hybrid:
    cf: 0.8
    steepness: 0.4
    inflection-point: 10
    alpha: 0.9